### ISSUE TITLE
As Anyone I need to setup Heroku environment

### ISSUE THREAD

**Issue by kallmanm** [Arcada-DevOps-MMMLS/Products#2]
setup

**Comment by kallmanm** [comment]
Databasen skall installeras i Heroku

**Comment by LukasLonnroth** [comment]
![screen shot 2018-09-27 at 14 49 57](https://user-images.githubusercontent.com/15245062/46144204-e8059c00-c264-11e8-93b3-1c42aff6eff1.png)
